trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  coverageResultFolder: '$(Build.SourcesDirectory)/TestResults/Coverage/'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:

- task: CacheBeta@1
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**'
    path: $(NUGET_PACKAGES)
  displayName: Cache NuGet packages

- task: DotNetCoreCLI@2
  displayName: install gitversion
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install gitversion.tool --tool-path .'
    includeNuGetOrg: true


- script: ./dotnet-gitversion > gitversion.json
  displayName: get gitversion

- task: oneLuckiDevJson2Variable@1
  displayName: parse gitversion
  inputs:
    jsonFile: 'gitversion.json'
    shouldPrefixVariables: true
    variablePrefix: 'gitversion'

- task: DotNetCoreCLI@2
  displayName: dotnet clean
  inputs:
    command: 'custom'
    custom: 'clean'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    includeNuGetOrg: true
    arguments: >-
      --configuration $(buildConfiguration)
      -p:Version=$(gitversion.SemVer)
      -p:AssemblyVersion=$(gitversion.AssemblySemVer)
      -p:FileVersion=$(gitversion.AssemblySemFileVer)

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    arguments: >-
      --configuration $(buildConfiguration) 
      --no-build
      -p:CollectCoverage=true 
      -p:CoverletOutputFormat=cobertura 
      -p:CoverletOutput=$(coverageResultFolder)

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(coverageResultFolder)/coverage.cobertura.xml'
    reportDirectory: '$(coverageResultFolder)/Report/'

- task: CopyFiles@2
  displayName: copy nuget for push
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src/TA.FluentValidation.Extensions.Options/bin/Release'
    Contents: |
      TA.FluentValidation.Extensions.Options.*.nupkg
      TA.FluentValidation.Extensions.Options.*.snupkg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script: > 
    dotnet nuget push 
    $(Build.ArtifactStagingDirectory)/TA.FluentValidation.Extensions.Options.*.nupkg 
    -k $NUGET_API_KEY 
    -s https://api.nuget.org/v3/index.json
  displayName: dotnet nuget push
  env:
    NUGET_API_KEY: $(NUGET_API_KEY)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Nuget package
  
- task: GitHubRelease@1
  displayName: create github release
  inputs:  
    gitHubConnection: 'github.com_tomek-anuszkiewicz'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(gitversion.SemVer)'
    releaseNotesSource: 'inline'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    assets: |
      $(Build.ArtifactStagingDirectory)/TA.FluentValidation.Extensions.Options.*.nupkg
      $(Build.ArtifactStagingDirectory)/TA.FluentValidation.Extensions.Options.*.snupkg
